language: erlang

otp_release:
  - 19.3
  - 23.0

os: linux

dist: xenial

services:
  - redis
  - postgresql

before_install:
  #
  # We need MySQL 5.6 or newer in order to get support for FULLTEXT indexes
  # with InnoDB. As soon as Travis ships that version, the following lines
  # (except for the "apt-get update" call) can go away.
  #
  # See: https://github.com/travis-ci/travis-ci/issues/1986
  #

install:
  - sudo apt-get -qq install libexpat1-dev libyaml-dev libpam0g-dev libsqlite3-dev libgd-dev libwebp-dev

script:
  - ./autogen.sh
  - which rebar3
  - ./configure --prefix=/tmp/ejabberd --enable-all --disable-odbc --disable-elixir --with-rebar=`which rebar3`
  - make
  - make install -s
  - make xref

notifications:
  email: false
